ci:
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: check-merge-conflict
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black-jupyter
        args: [--skip-string-normalization]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        additional_dependencies: [numpy>=1.22.2]
# jupyter hooks
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
    -   id: nbqa
        name: mypy-juypter
        args: [mypy, --ignore-missing-imports, --scripts-are-modules]
        additional_dependencies: [reorder-python-imports, mypy, numpy>=1.22.2]
    -   id: nbqa
        name: Reorder python import-jupyter
        args: [reorder_python_imports]
        additional_dependencies: [reorder-python-imports]
        # the hook below are called via an unsupported interface, this may break at some point
    -   id: nbqa
        name: double-quote-string-fixer-jupyter
        args: [pre_commit_hooks.string_fixer]
        additional_dependencies: [pre-commit-hooks]
    -   id: nbqa
        name: debug-statements-jupyter
        args: [pre_commit_hooks.debug_statement_hook]
        additional_dependencies: [pre-commit-hooks]
